##Description##
请描述该ETL任务, 方便理解代码内容, 例如该任务产生什么数据、用于支持什么需求等
## 2026-06-01 Spark 内存优化 V2：
## - spark.executor.memory: 1536m → 1280m（GC仅3.5%，堆内内存充裕，节省16.7%）
## - spark.yarn.executor.memoryOverhead: 768m（保持不变，V1降为512m导致OOM-executor-overhead）
## - spark.dynamicAllocation.maxExecutors: 500 → 300（峰值executor数275，×1.1余量）
## - YARN每executor分配: 2304m → 2048m（总节省11.1%）

##Extract##
## 这里填写一个能读取source库下数据sql, 读出的数据会load到target库，hive2hive流程请留空

##Preload##
## 这里可以写load数据之前执行的SQL，例如清理数据、删除特定分区等，不需要请留空

##Load##
## 这里填写一个能load数据的SQL，非hive2hive流程请留空
## 注意：注释参数请使用##，--注释仅对SQL语句生效
## 下面参数的含义可以去https://km.sankuai.com/page/124233475中查看详细的解释
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;
SET hive.exec.max.dynamic.partitions=1000;
SET hive.default.fileformat=orc;
## 提升资源利用率，降低内存申请量，绝大多数任务memory+memoryOverhead<=2304M是可行的，既不会延长任务执行时间，也可以节省计算资源开销
## 注意：内存的调整要以256M的倍数为单位进行增减，即memory+memoryOverhead要是256M的整数倍。如果调整为1025M，实际生效是1024+256=1280M
SET spark.executor.memory=4096M;              ## 【2026-06-01 内存优化V2】原值1536M -> 1280M（GC仅3.5%，堆内充裕，节省16.7%）
SET spark.yarn.executor.memoryOverhead=1024M;  ## 【2026-06-01 内存优化V2】保持768M不变（V1降512M导致OOM-overhead）
SET spark.memory.fraction=0.7;                ## 提高统一内存的比例，0.5-0.7都可以，如果使用udf中有大量内部变量，会有oom风险，可适当调小
## 控制map和reduce处理的文件大小
SET spark.hadoopRDD.targetBytesInPartition=134217728;                  ## 控制了orc.split.strategy=ETL时的文件切分大小，也变相控制了map stage的输出大小
SET spark.sql.adaptive.shuffle.targetPostShuffleInputSize=33554432;   ## shuffle read一般控制在128-256m之间；如果有数据膨胀可以调小（以shuffle write的数据量为判断依据）
## 小文件合并
SET spark.sql.mergeSmallFileSize=33554432;                 ## 小于32m启动合并，对于多分区的大表来说低于100m都可以考虑启动文件合并
SET spark.sql.targetBytesInPartitionWhenMerge=134217728;   ## 128m，设置为64-256m之间比较合适
## 控制申请的executor的并发数量
## 这是一个根据任务调整的参数，不是对时效性要求高的任务不设置太大的并发。非SLA任务executor*core和最大stage的task数量控制在1:5或1:10，SLA任务控制在1:5到1:2之间。
SET spark.dynamicAllocation.maxExecutors=2000;        ## 【2026-06-01 内存优化】原值500 -> 300（峰值executor数275，×1.1≈300）
## 控制partition的最大并行度
## 这是一个根据任务调整的参数，spark3中这里设置的是最大partition数量，如果数据量很大（尤其是peak day数据量很大）可以酌情调大
SET spark.sql.shuffle.partitions=4000;
## SET spark.shuffle.manager=rss; ##只有在SLA中的任务，RSS参数才是有效的，可以根据任务权重是否有A或S判断，比如任务权重是 0S_15A_742B，则是SLA任务

INSERT OVERWRITE TABLE `${target.table}` PARTITION (dt,level3_biz_code)
SELECT
    a.session_id,
    COUNT(DISTINCT IF(c.is_holiday_weekend_vacation = 1, c.checkin_datekey, null)) AS holiday_weekend_vacation_checkin_datekey_cnt,
    COUNT(DISTINCT IF(c.is_holiday = 1, c.checkin_datekey, null)) AS holiday_checkin_datekey_cnt,
    COUNT(DISTINCT IF(c.is_weekend = 1, c.checkin_datekey, null)) AS weekend_checkin_datekey_cnt,
    COUNT(DISTINCT IF(c.is_vacation = 1, c.checkin_datekey, null)) AS vacation_checkin_datekey_cnt,
    AVG(c.lead_time) AS lead_time,
    COUNT(DISTINCT c.checkin_datekey) AS checkin_datekey_cnt,
    COUNT(DISTINCT c.goods_id) AS goods_cnt,
    COUNT(DISTINCT c.poi_id) AS poi_cnt,
    COUNT(DISTINCT c.yx_id) AS aoi_cnt,
    COUNT(DISTINCT c.city_location_name) AS city_cnt,
    SUM(COALESCE(c.page_stay_time, 0)) / 1000 AS stay_time,
    COUNT(IF(c.page_type IN ('hotel_search_mid_page', 'poi_list_bigsearch'), c.event_identifier, null)) AS search_page_cnt,
    SUM(COALESCE(IF(c.page_type IN ('hotel_search_mid_page', 'poi_list_bigsearch'), c.page_stay_time, 0), 0)) / 1000 AS search_page_time,
    COUNT(IF(c.page_type IN ('poilist', 'poi_list'), c.event_identifier, null)) AS poi_list_cnt,
    SUM(COALESCE(IF(c.page_type IN ('poilist', 'poi_list'), c.page_stay_time, 0), 0)) / 1000 AS poi_list_time,
    COUNT(IF(c.page_type IN ('poi', 'poi_info'), c.event_identifier, null)) AS poi_info_cnt,
    SUM(COALESCE(IF(c.page_type IN ('poi', 'poi_info'), c.page_stay_time, 0), 0)) / 1000 AS poi_info_time,
    COUNT(IF(c.page_type = 'room_list', c.event_identifier, null)) AS room_list_cnt,
    SUM(COALESCE(IF(c.page_type = 'room_list', c.page_stay_time, 0), 0)) / 1000 AS room_list_time,
    COUNT(IF(c.page_type = 'room_detail_page', c.event_identifier, null)) AS room_info_cnt,
    SUM(COALESCE(IF(c.page_type = 'room_detail_page', c.page_stay_time, 0), 0)) / 1000 AS room_info_time,
    COUNT(IF(c.page_type IN ('bookpoiorder', 'create_order'), c.event_identifier, null)) AS create_order_cnt,
    SUM(COALESCE(IF(c.page_type IN ('bookpoiorder', 'create_order'), c.page_stay_time, 0), 0)) / 1000 AS create_order_time,
    COUNT(IF(c.page_type IN ('user_comment_page', 'evaluate_list_page', 'evaluate_submit_page'), c.event_identifier, null)) AS evaluate_page_cnt,
    SUM(COALESCE(IF(c.page_type IN ('user_comment_page', 'evaluate_list_page', 'evaluate_submit_page'), c.page_stay_time, 0), 0)) / 1000 AS evaluate_page_time,
    SUM(c.is_search_scenic) AS search_scenic_cnt,
    SUM(c.is_waitou) AS waitou_cnt,
    SUM(c.is_rednote) AS rednote_cnt,
    SUM(c.is_order) AS order_cnt,
    SUM(c.is_star2) AS star2_cnt,
    SUM(c.is_star3) AS star3_cnt,
    SUM(c.is_star4) AS star4_cnt,
    SUM(c.is_star5) AS star5_cnt,
    SUM(c.is_budget) AS budget_cnt,
    SUM(c.is_express) AS express_cnt,
    SUM(c.is_business) AS business_cnt,
    SUM(c.is_theme) AS theme_cnt,
    SUM(c.is_couple) AS couple_cnt,
    SUM(c.is_apartment) AS apartment_cnt,
    SUM(c.is_inn) AS inn_cnt,
    SUM(c.is_homestay) AS homestay_cnt,
    SUM(c.is_hostel) AS hostel_cnt,
    SUM(c.is_farmstay) AS farmstay_cnt,
    SUM(c.is_family_guesthouse) AS family_guesthouse_cnt,
    SUM(c.is_guesthouse) AS guesthouse_cnt,
    SUM(c.is_resort_hotel) AS resort_hotel_cnt,
    SUM(c.is_villa) AS villa_cnt,
    SUM(c.is_family) AS family_cnt,
    SUM(c.is_esports) AS esports_cnt,
    SUM(c.is_scarce) AS scarce_cnt,
    SUM(c.is_unique) AS unique_cnt,
    SUM(c.is_lowprice) AS lowprice_cnt,
    SUM(c.is_good) AS good_cnt,
    SUM(c.is_tourism_core_city) AS tourism_core_city_cnt,
    SUM(c.is_tourism_big_city) AS tourism_big_city_cnt,
    SUM(c.is_tourism_seasonal_city) AS tourism_seasonal_city_cnt,
    SUM(c.is_tier1_city) AS tier1_city_cnt,
    SUM(c.is_new_tier1_city) AS new_tier1_city_cnt,
    SUM(c.is_tier2_city) AS tier2_city_cnt,
    SUM(c.is_tier3_city) AS tier3_city_cnt,
    SUM(c.is_tier4_city) AS tier4_city_cnt,
    SUM(c.is_tier5_city) AS tier5_city_cnt,
    SUM(c.is_university) AS university_cnt,
    SUM(c.is_transportation_hub) AS transportation_hub_cnt,
    SUM(c.is_scenic_area) AS scenic_area_cnt,
    SUM(c.is_hospital) AS hospital_cnt,
    SUM(c.is_performance_sports_venue) AS performance_sports_venue_cnt,
    SUM(c.is_convention_center) AS convention_center_cnt,
    SUM(c.is_industrial_park) AS industrial_park_cnt,
    SUM(c.is_king_room) AS king_room_cnt,
    SUM(c.is_single_room) AS single_room_cnt,
    SUM(c.is_double_room) AS double_room_cnt,
    SUM(c.is_triple_room) AS triple_room_cnt,
    SUM(c.is_suite) AS suite_cnt,
    SUM(c.is_standalone) AS standalone_cnt,
    SUM(c.is_dorm) AS dorm_cnt,
    MAX(c.is_college_student) AS is_college_student,
    MAX(c.is_adult_single) AS is_adult_single,
    MAX(c.is_adult_married_no_kids) AS is_adult_married_no_kids,
    MAX(c.is_adult_married_with_kids) AS is_adult_married_with_kids,
    MAX(c.is_over_60) AS is_over_60,
    MAX(c.is_senior) AS is_senior,
    MAX(c.is_middle_age) AS is_middle_age,
    MAX(c.is_young) AS is_young,
    MAX(c.is_minor) AS is_minor,
    MAX(c.is_high_value) AS is_high_value,
    MAX(c.is_mid_value) AS is_mid_value,
    MAX(c.is_low_value) AS is_low_value,
    MAX(c.is_l4) AS is_l4,
    MAX(c.is_l1_3) AS is_l1_3,
    MAX(c.is_youth_campus) AS is_youth_campus,
    MAX(c.is_business_elite) AS is_business_elite,
    MAX(c.is_self_social) AS is_self_social,
    MAX(c.is_practical_life) AS is_practical_life,
    MAX(c.is_family_guardian) AS is_family_guardian,
    MAX(c.is_vital_soldier) AS is_vital_soldier,
    MAX(c.is_quality_visitor) AS is_quality_visitor,
    MAX(c.is_kid_explorer) AS is_kid_explorer,
    MAX(c.is_occasional_traveler) AS is_occasional_traveler,
    SUM(c.holiday_rnt) / NULLIF(SUM(c.rnt), 0) AS holiday_rnt_pct,
    AVG(c.travel_distance) AS travel_distance,
    MAX(IF(c.is_order = 1, c.is_holiday_weekend_vacation, 0)) AS is_holiday_weekend_vacation,
    MAX(IF(c.is_order = 1, c.is_holiday, 0)) AS is_holiday,
    MAX(IF(c.is_order = 1, c.is_weekend, 0)) AS is_weekend,
    MAX(IF(c.is_order = 1, c.is_vacation, 0)) AS is_vacation,
    AVG(IF(c.is_order = 1, c.lead_time, null)) AS order_lead_time,
    MAX(IF(c.is_order = 1, c.is_search_scenic, 0)) AS is_search_scenic,
    MAX(IF(c.is_order = 1, c.is_waitou, 0)) AS is_waitou,
    MAX(IF(c.is_order = 1, c.is_rednote, 0)) AS is_rednote,
    MAX(IF(c.is_order = 1, c.is_star2, 0)) AS is_star2,
    MAX(IF(c.is_order = 1, c.is_star3, 0)) AS is_star3,
    MAX(IF(c.is_order = 1, c.is_star4, 0)) AS is_star4,
    MAX(IF(c.is_order = 1, c.is_star5, 0)) AS is_star5,
    MAX(IF(c.is_order = 1, c.is_budget, 0)) AS is_budget,
    MAX(IF(c.is_order = 1, c.is_express, 0)) AS is_express,
    MAX(IF(c.is_order = 1, c.is_business, 0)) AS is_business,
    MAX(IF(c.is_order = 1, c.is_theme, 0)) AS is_theme,
    MAX(IF(c.is_order = 1, c.is_couple, 0)) AS is_couple,
    MAX(IF(c.is_order = 1, c.is_apartment, 0)) AS is_apartment,
    MAX(IF(c.is_order = 1, c.is_inn, 0)) AS is_inn,
    MAX(IF(c.is_order = 1, c.is_homestay, 0)) AS is_homestay,
    MAX(IF(c.is_order = 1, c.is_hostel, 0)) AS is_hostel,
    MAX(IF(c.is_order = 1, c.is_farmstay, 0)) AS is_farmstay,
    MAX(IF(c.is_order = 1, c.is_family_guesthouse, 0)) AS is_family_guesthouse,
    MAX(IF(c.is_order = 1, c.is_guesthouse, 0)) AS is_guesthouse,
    MAX(IF(c.is_order = 1, c.is_resort_hotel, 0)) AS is_resort_hotel,
    MAX(IF(c.is_order = 1, c.is_villa, 0)) AS is_villa,
    MAX(IF(c.is_order = 1, c.is_family, 0)) AS is_family,
    MAX(IF(c.is_order = 1, c.is_esports, 0)) AS is_esports,
    MAX(IF(c.is_order = 1, c.is_scarce, 0)) AS is_scarce,
    MAX(IF(c.is_order = 1, c.is_unique, 0)) AS is_unique,
    MAX(IF(c.is_order = 1, c.is_lowprice, 0)) AS is_lowprice,
    MAX(IF(c.is_order = 1, c.is_good, 0)) AS is_good,
    MAX(IF(c.is_order = 1, c.travel_distance, 0)) AS order_travel_distance,
    MAX(IF(c.is_order = 1, c.is_tourism_core_city, 0)) AS is_tourism_core_city,
    MAX(IF(c.is_order = 1, c.is_tourism_big_city, 0)) AS is_tourism_big_city,
    MAX(IF(c.is_order = 1, c.is_tourism_seasonal_city, 0)) AS is_tourism_seasonal_city,
    MAX(IF(c.is_order = 1, c.is_tier1_city, 0)) AS is_tier1_city,
    MAX(IF(c.is_order = 1, c.is_new_tier1_city, 0)) AS is_new_tier1_city,
    MAX(IF(c.is_order = 1, c.is_tier2_city, 0)) AS is_tier2_city,
    MAX(IF(c.is_order = 1, c.is_tier3_city, 0)) AS is_tier3_city,
    MAX(IF(c.is_order = 1, c.is_tier4_city, 0)) AS is_tier4_city,
    MAX(IF(c.is_order = 1, c.is_tier5_city, 0)) AS is_tier5_city,
    MAX(IF(c.is_order = 1, c.is_university, 0)) AS is_university,
    MAX(IF(c.is_order = 1, c.is_transportation_hub, 0)) AS is_transportation_hub,
    MAX(IF(c.is_order = 1, c.is_scenic_area, 0)) AS is_scenic_area,
    MAX(IF(c.is_order = 1, c.is_hospital, 0)) AS is_hospital,
    MAX(IF(c.is_order = 1, c.is_performance_sports_venue, 0)) AS is_performance_sports_venue,
    MAX(IF(c.is_order = 1, c.is_convention_center, 0)) AS is_convention_center,
    MAX(IF(c.is_order = 1, c.is_industrial_park, 0)) AS is_industrial_park,
    MAX(IF(c.is_order = 1, c.is_king_room, 0)) AS is_king_room,
    MAX(IF(c.is_order = 1, c.is_single_room, 0)) AS is_single_room,
    MAX(IF(c.is_order = 1, c.is_double_room, 0)) AS is_double_room,
    MAX(IF(c.is_order = 1, c.is_triple_room, 0)) AS is_triple_room,
    MAX(IF(c.is_order = 1, c.is_suite, 0)) AS is_suite,
    MAX(IF(c.is_order = 1, c.is_standalone, 0)) AS is_standalone,
    MAX(IF(c.is_order = 1, c.is_dorm, 0)) AS is_dorm,
    sum(c.is_search) AS search_cnt,
    sum(c.is_travel_session) AS travel_session_cnt,
    MAX(IF(c.is_order = 1, c.is_search, 0)) AS is_search,
    MAX(IF(c.is_order = 1, c.is_travel_session, 0)) AS is_travel_session,
    COUNT(DISTINCT c.session_id) AS session_cnt,
    COUNT(DISTINCT c.event_identifier) AS event_cnt,
    COUNT(DISTINCT IF(c.lead_time > 0, c.checkin_datekey, null)) AS advance_checkin_datekey_cnt,
    COUNT(DISTINCT IF(c.lead_time = 0, c.checkin_datekey, null)) AS sameday_checkin_datekey_cnt,
    COUNT(DISTINCT IF(c.lead_time < 0, c.checkin_datekey, null)) AS overnight_checkin_datekey_cnt,
    a.dt,
    'hotel' AS level3_biz_code
FROM (
    SELECT DISTINCT
        session_id,
        dt
    FROM mart_jiulv_flow.dws_stp_session_detail_df
    WHERE dt = $now.datekey
    and level3_biz_code = 'hotel'
) a
INNER JOIN (
    SELECT DISTINCT
        session_id,
        related_session_id
    FROM mart_jiulv_flow.dim_stp_session_rel_df
    WHERE dt = $now.datekey
    and level3_biz_code = 'hotel'
) b
    ON a.session_id = b.session_id
LEFT JOIN (
    SELECT checkin_datekey,
            session_id,
            device_id,
            user_key,
            city_location_name,
            yx_id,
            poi_id,
            goods_id,
            page_type,
            page_stay_time,
            event_identifier,
            is_holiday_weekend_vacation,
            is_holiday,
            is_weekend,
            is_vacation,
            is_booking_weekend,
            lead_time,
            latitude,
            longitude,
            is_star2,
            is_star3,
            is_star4,
            is_star5,
            is_budget,
            is_express,
            is_business,
            is_theme,
            is_couple,
            is_apartment,
            is_inn,
            is_homestay,
            is_hostel,
            is_farmstay,
            is_family_guesthouse,
            is_guesthouse,
            is_resort_hotel,
            is_villa,
            is_family,
            is_esports,
            is_scarce,
            is_unique,
            is_lowprice,
            is_good,
            is_tourism_core_city,
            is_tourism_big_city,
            is_tourism_seasonal_city,
            is_tier1_city,
            is_new_tier1_city,
            is_tier2_city,
            is_tier3_city,
            is_tier4_city,
            is_tier5_city,
            is_university,
            is_transportation_hub,
            is_scenic_area,
            is_hospital,
            is_performance_sports_venue,
            is_convention_center,
            is_industrial_park,
            is_king_room,
            is_single_room,
            is_double_room,
            is_triple_room,
            is_suite,
            is_standalone,
            is_dorm,
            is_search_scenic,
            is_waitou,
            is_rednote,
            is_order,
            is_order_city,
            is_order_aoi,
            is_order_poi,
            is_order_goods,
            order_key,
            is_college_student,
            is_adult_single,
            is_adult_married_no_kids,
            is_adult_married_with_kids,
            is_over_60,
            is_senior,
            is_middle_age,
            is_young,
            is_minor,
            home_location,
            is_high_value,
            is_mid_value,
            is_low_value,
            is_l4,
            is_l1_3,
            is_youth_campus,
            is_business_elite,
            is_self_social,
            is_practical_life,
            is_family_guardian,
            is_vital_soldier,
            is_quality_visitor,
            is_kid_explorer,
            is_occasional_traveler,
            holiday_rnt,
            rnt,
            travel_distance,
            is_search ,
            is_travel_session,
            dt,
            level3_biz_code
    FROM mart_jiulv_flow.dws_stp_session_detail_df
    WHERE dt BETWEEN $now.delta(30).datekey AND $now.datekey
    and level3_biz_code = 'hotel'
) c
    ON b.related_session_id = c.session_id
GROUP BY
    a.session_id,
    a.dt
;

##TargetDDL##
## 填写目标表的表结构定义，用于目标表不存在的时候根据ddl建表。请确保sql中的字段和ddl中的字段的数量、顺序一致！！
CREATE TABLE IF NOT EXISTS `${target.table}`
(
    session_id                                   string COMMENT 'session_id',
    holiday_weekend_vacation_checkin_datekey_cnt int    COMMENT '节日/周末/假期入住日期浏览次数',
    holiday_checkin_datekey_cnt                  int    COMMENT '节日入住日期浏览次数',
    weekend_checkin_datekey_cnt                  int    COMMENT '周末入住日期浏览次数',
    vacation_checkin_datekey_cnt                 int    COMMENT '假期入住日期浏览次数',
    lead_time                                    double COMMENT '平均浏览入住日期提前订天数',
    checkin_datekey_cnt                          int    COMMENT '入住日期浏览次数',
    goods_cnt                                    int    COMMENT 'goods浏览次数',
    poi_cnt                                      int    COMMENT 'poi浏览次数',
    aoi_cnt                                      int    COMMENT 'aoi浏览次数',
    city_cnt                                     int    COMMENT '城市浏览次数',
    stay_time                                    double COMMENT '浏览总时长',
    search_page_cnt                              int    COMMENT '搜索页浏览次数',
    search_page_time                             double COMMENT '搜索页浏览时长',
    poi_list_cnt                                 int    COMMENT 'poi列表页浏览次数',
    poi_list_time                                double COMMENT 'poi列表页浏览时长',
    poi_info_cnt                                 int    COMMENT 'poi详情页浏览次数',
    poi_info_time                                double COMMENT 'poi详情页浏览时长',
    room_list_cnt                                int    COMMENT 'goods列表页浏览次数',
    room_list_time                               double COMMENT 'goods列表页浏览时长',
    room_info_cnt                                int    COMMENT 'goods详情页浏览次数',
    room_info_time                               double COMMENT 'goods详情页浏览时长',
    create_order_cnt                             int    COMMENT '创建订单页浏览次数',
    create_order_time                            double COMMENT '创建订单页浏览时长',
    evaluate_page_cnt                            int    COMMENT '评价页浏览次数',
    evaluate_page_time                           double COMMENT '评价页浏览时长',
    search_scenic_cnt                            int    COMMENT '是否搜索景区',
    waitou_cnt                                   int    COMMENT '是否外投来源',
    rednote_cnt                                  int    COMMENT '是否小红书来源',
    order_cnt                                    int    COMMENT '是否下单',
    star2_cnt                                    int    COMMENT '0-2星酒店浏览次数',
    star3_cnt                                    int    COMMENT '3星酒店浏览次数',
    star4_cnt                                    int    COMMENT '4星酒店浏览次数',
    star5_cnt                                    int    COMMENT '5星酒店浏览次数',
    budget_cnt                                   int    COMMENT '经济型酒店浏览次数',
    express_cnt                                  int    COMMENT '快捷酒店浏览次数',
    business_cnt                                 int    COMMENT '商务酒店浏览次数',
    theme_cnt                                    int    COMMENT '主题酒店浏览次数',
    couple_cnt                                   int    COMMENT '情侣酒店浏览次数',
    apartment_cnt                                int    COMMENT '公寓浏览次数',
    inn_cnt                                      int    COMMENT '客栈浏览次数',
    homestay_cnt                                 int    COMMENT '民宿浏览次数',
    hostel_cnt                                   int    COMMENT '青年旅社浏览次数',
    farmstay_cnt                                 int    COMMENT '农家院浏览次数',
    family_guesthouse_cnt                        int    COMMENT '家庭旅馆浏览次数',
    guesthouse_cnt                               int    COMMENT '招待所浏览次数',
    resort_hotel_cnt                             int    COMMENT '度假酒店浏览次数',
    villa_cnt                                    int    COMMENT '别墅浏览次数',
    family_cnt                                   int    COMMENT '亲子酒店浏览次数',
    esports_cnt                                  int    COMMENT '电竞酒店浏览次数',
    scarce_cnt                                   int    COMMENT '稀缺poi浏览次数',
    unique_cnt                                   int    COMMENT '特色品质poi浏览次数',
    lowprice_cnt                                 int    COMMENT '低价同质poi浏览次数',
    good_cnt                                     int    COMMENT '物好poi浏览次数',
    tourism_core_city_cnt                        int    COMMENT '旅游产业支柱型城市浏览次数',
    tourism_big_city_cnt                         int    COMMENT '大体量旅游收入城市浏览次数',
    tourism_seasonal_city_cnt                    int    COMMENT '季节性旅游城市浏览次数',
    tier1_city_cnt                               int    COMMENT '一线城市浏览次数',
    new_tier1_city_cnt                           int    COMMENT '新一线城市浏览次数',
    tier2_city_cnt                               int    COMMENT '二线城市浏览次数',
    tier3_city_cnt                               int    COMMENT '三线城市浏览次数',
    tier4_city_cnt                               int    COMMENT '四线城市浏览次数',
    tier5_city_cnt                               int    COMMENT '五线城市浏览次数',
    university_cnt                               int    COMMENT '大学aoi浏览次数',
    transportation_hub_cnt                       int    COMMENT '交通枢纽aoi浏览次数',
    scenic_area_cnt                              int    COMMENT '景区aoi浏览次数',
    hospital_cnt                                 int    COMMENT '医院aoi浏览次数',
    performance_sports_venue_cnt                 int    COMMENT '文体场馆aoi浏览次数',
    convention_center_cnt                        int    COMMENT '会展中心aoi浏览次数',
    industrial_park_cnt                          int    COMMENT '产业园区aoi浏览次数',
    king_room_cnt                                int    COMMENT '大床房型浏览次数',
    single_room_cnt                              int    COMMENT '单人房型浏览次数',
    double_room_cnt                              int    COMMENT '双人房型浏览次数',
    triple_room_cnt                              int    COMMENT '三人房型浏览次数',
    suite_cnt                                    int    COMMENT '套房房型浏览次数',
    standalone_cnt                               int    COMMENT '独栋房型浏览次数',
    dorm_cnt                                     int    COMMENT '床位房型浏览次数',
    is_college_student                           int    COMMENT '是否大学生',
    is_adult_single                              int    COMMENT '是否单身成人',
    is_adult_married_no_kids                     int    COMMENT '是否已婚无孩成人',
    is_adult_married_with_kids                   int    COMMENT '是否已婚有孩成人',
    is_over_60                                   int    COMMENT '是否60岁以上',
    is_senior                                    int    COMMENT '是否老年人',
    is_middle_age                                int    COMMENT '是否中年人',
    is_young                                     int    COMMENT '是否年轻人',
    is_minor                                     int    COMMENT '是否未成年人',
    is_high_value                                int    COMMENT '是否高价值用户',
    is_mid_value                                 int    COMMENT '是否中价值用户',
    is_low_value                                 int    COMMENT '是否低价值用户',
    is_l4                                        int    COMMENT '是否L4+用户',
    is_l1_3                                      int    COMMENT '是否L1-L3用户',
    is_youth_campus                              int    COMMENT '是否青春校园族',
    is_business_elite                            int    COMMENT '是否商务精英党',
    is_self_social                               int    COMMENT '是否悦己社交派',
    is_practical_life                            int    COMMENT '是否务实生活党',
    is_family_guardian                           int    COMMENT '是否家庭守护者',
    is_vital_soldier                             int    COMMENT '是否活力特种兵',
    is_quality_visitor                           int    COMMENT '是否品质漫游客',
    is_kid_explorer                              int    COMMENT '是否带娃探索家',
    is_occasional_traveler                       int    COMMENT '是否偶发出行者',
    holiday_rnt_pct                              double COMMENT '假期入住间夜占比',
    travel_distance                              double COMMENT '平均出行距离',
    is_holiday_weekend_vacation                  int    COMMENT '是否下单节日/周末/假期',
    is_holiday                                   int    COMMENT '是否下单节日',
    is_weekend                                   int    COMMENT '是否下单周末',
    is_vacation                                  int    COMMENT '是否下单假期',
    order_lead_time                              double COMMENT '下单提前订天数',
    is_star2                                     int    COMMENT '是否下单0-2星酒店',
    is_star3                                     int    COMMENT '是否下单3星酒店',
    is_star4                                     int    COMMENT '是否下单4星酒店',
    is_star5                                     int    COMMENT '是否下单5星酒店',
    is_budget                                    int    COMMENT '是否下单经济型酒店',
    is_express                                   int    COMMENT '是否下单快捷酒店',
    is_business                                  int    COMMENT '是否下单商务酒店',
    is_theme                                     int    COMMENT '是否下单主题酒店',
    is_couple                                    int    COMMENT '是否下单情侣酒店',
    is_apartment                                 int    COMMENT '是否下单公寓',
    is_inn                                       int    COMMENT '是否下单客栈',
    is_homestay                                  int    COMMENT '是否下单民宿',
    is_hostel                                    int    COMMENT '是否下单青年旅舍',
    is_farmstay                                  int    COMMENT '是否下单农家院',
    is_family_guesthouse                         int    COMMENT '是否下单家庭旅馆',
    is_guesthouse                                int    COMMENT '是否下单招待所',
    is_resort_hotel                              int    COMMENT '是否下单度假酒店',
    is_villa                                     int    COMMENT '是否下单别墅',
    is_family                                    int    COMMENT '是否下单亲子酒店',
    is_esports                                   int    COMMENT '是否下单电竞酒店',
    is_scarce                                    int    COMMENT '是否下单稀缺poi',
    is_unique                                    int    COMMENT '是否下单特色品质poi',
    is_lowprice                                  int    COMMENT '是否下单低价同质poi',
    is_good                                      int    COMMENT '是否下单物好poi',
    order_travel_distance                        double COMMENT '下单出行距离',
    is_search_scenic                             int    COMMENT '是否下单搜索景区',
    is_waitou                                    int    COMMENT '是否下单外投来源',
    is_rednote                                   int    COMMENT '是否下单小红书来源',
    is_tourism_core_city                         int    COMMENT '是否下单旅游产业支柱型城市',
    is_tourism_big_city                          int    COMMENT '是否下单大体量旅游收入城市',
    is_tourism_seasonal_city                     int    COMMENT '是否下单季节性旅游城市',
    is_tier1_city                                int    COMMENT '是否下单一线城市',
    is_new_tier1_city                            int    COMMENT '是否下单新一线城市',
    is_tier2_city                                int    COMMENT '是否下单二线城市',
    is_tier3_city                                int    COMMENT '是否下单三线城市',
    is_tier4_city                                int    COMMENT '是否下单四线城市',
    is_tier5_city                                int    COMMENT '是否下单五线城市',
    is_university                                int    COMMENT '是否下单大学aoi',
    is_transportation_hub                        int    COMMENT '是否下单交通枢纽aoi',
    is_scenic_area                               int    COMMENT '是否下单景区aoi',
    is_hospital                                  int    COMMENT '是否下单医院aoi',
    is_performance_sports_venue                  int    COMMENT '是否下单文体场馆aoi',
    is_convention_center                         int    COMMENT '是否下单会展中心aoi',
    is_industrial_park                           int    COMMENT '是否下单产业园区下单',
    is_king_room                                 int    COMMENT '是否下单大床房型',
    is_single_room                               int    COMMENT '是否下单单人房型',
    is_double_room                               int    COMMENT '是否下单双人房型',
    is_triple_room                               int    COMMENT '是否下单三人房型',
    is_suite                                     int    COMMENT '是否下单套房房型',
    is_standalone                                int    COMMENT '是否下单独栋房型',
    is_dorm                                      int    COMMENT '是否下单床位房型',
    search_cnt                                   int    COMMENT '搜索次数',  
    travel_session_cnt                           int    COMMENT '同日同城存在门票/度假行为次数',
    is_search                                    int    COMMENT '是否下单搜索',
    is_travel_session                            int    COMMENT '是否下单且同日同城存在门票/度假行为',
    session_cnt                                  int    COMMENT '关联session个数',
    event_cnt                                    int    COMMENT '关联event_identifier个数',
    advance_checkin_datekey_cnt                  int    COMMENT '提前预订入住日期个数',
    sameday_checkin_datekey_cnt                  int    COMMENT '当日预订入住日期个数',
    overnight_checkin_datekey_cnt                int    COMMENT '过夜预订入住日期个数'
)
COMMENT 'session聚合表'
PARTITIONED BY (dt string COMMENT '日期分区字段，格式为dt(yyyymmdd)',level3_biz_code string COMMENT '三级业务编码：hotel-酒店，homestay-民宿，ticket-景点游玩，vacation-度假，zuche-租车，flight-机票，train-火车票，coach-汽车票')
STORED AS ORC
;
